apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: IMAGE_PLACEHOLDER
          command: ["dotnet", "FiapCloudGamesCatalog.Api.dll", "migrate"]
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secrets 
      restartPolicy: Never