apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migration
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: migration
          image: fgcacr13245.azurecr.io/antniocarlodfiapcloudgamescatalogapi:$(tag)
          command: ["dotnet", "FiapCloudGamesCatalog.Api.dll", "migrate"]
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secrets 
      restartPolicy: Never