apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  ConnectionStrings__MySQL: "Server=fiapcloudgamesdb.mysql.database.azure.com;Database=catalog_db;Uid=usr_catalog;Pwd=catalog123;"

  Authentication__Key: "HvPmUQ7j9ygSJ5DYDyOOPFjj0DRC6RDCi03GUR0uo8GZQEWACVqrY1xEqfdA"

  ElasticSearch__ApiKey: "ZHRwN3dwc0J0STRlQXlkWGVhRUs6MjhqNFpOUEdMZVdIeG1sMzRUUUhPUQ=="

  AzureServiceBus__ConnectionString: "Endpoint=sb://fiapcloudgamessb123.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=/nKHQNI7AL4LVoNOV1lUCFj1HXaXBUWX0+ASbJhypVQ="
  
  Redis__ConnectionString: "fgc.centralus.redis.azure.net:10000,password=1h7X5JZZsKeAkcjZ0b-U0WEhlI60Zi-tQAZCACq0hB4=,ssl=True,abortConnect=False,sslProtocols=Tls12"

  MongoCatalog__ConnectionString: "mongodb+srv://antonioalbertoestudo_db_user:chWaPZ9O5GNd91kR@fgc-mongo-cluster.5p4upvr.mongodb.net/?appName=fgc-mongo-cluster"