apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  ConnectionStrings__MySQL: "#{ConnectionStrings__MySQL}#"

  Authentication__Key: "#{Authentication__Key}#"

  ElasticSearch__ApiKey: "#{ElasticSearch__ApiKey}#"

  AzureServiceBus__ConnectionString: "#{AzureServiceBus__ConnectionString}#"
  
  Redis__ConnectionString: "#{Redis__ConnectionString}#"

  MongoCatalog__ConnectionString: "#{MongoCatalog__ConnectionString}#"